#deployment.yaml file

apiVersion: apps/v1

kind: Deployment

metadata:

  name: myapp-deployment2

spec:

  replicas: 1

  selector:

    matchLabels:

      app: myapp

  template:

    metadata:

      labels:

        app: myapp

    spec:

      containers:

      - name: myapp

        image: kubesamm/myapp:v1

        ports:

        - containerPort: 5000
